title: Mason Nakamura
logo: /assets/img/Mason_Photo.JPG
description: Personal Website
show_downloads: true
google_analytics: G-HK6QKBXJ34
remote_theme: gebeto/researcher

footer: "Page design by Ankit Sultana"
footer_url: "https://github.com/ankitsultana"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
