title: Researcher
logo: /assets/img/logo.png
description: Researcher is a theme for GitHub Pages.
show_downloads: false
google_analytics: UA-120902316-1
remote_theme: gebeto/researcher


nav:
 - name: "Contact"
   link: "contact"
 - name: "Resume"
   link: "resume.pdf" # put your files in the assets directory
 - name: "About"
   link: "/researcher/"


footer: "Page design by Ankit Sultana"
footer_url: "https://github.com/ankitsultana"